import { TC_LIGHT } from "../../theme.js";

export const sharedStyles = {
  card: (tc = TC_LIGHT) => ({ background: tc.card, border: `1px solid ${tc.border}`, borderRadius: "var(--radius-md)" }),
  cardPad: (tc = TC_LIGHT, pad = "var(--space-5) var(--space-6)") => ({ ...sharedStyles.card(tc), padding: pad }),
  th: (tc = TC_LIGHT) => ({ padding: "var(--space-2) var(--space-3)", fontSize: "var(--text-xs)", letterSpacing: "0.05em", textTransform: "uppercase", color: tc.textLight, fontWeight: 600 }),
  sec: (tc = TC_LIGHT) => ({ fontSize: "var(--text-xs)", letterSpacing: "0.05em", textTransform: "uppercase", color: tc.textLight, fontWeight: 600 }),
  badge: (_tc = TC_LIGHT) => ({ fontSize: "var(--text-xs)", borderRadius: "var(--radius-sm)", padding: "2px 7px", fontWeight: 600, whiteSpace: "nowrap", display: "inline-block" }),
  kpi: (tc = TC_LIGHT) => ({ background: tc.card, border: `1px solid ${tc.border}`, borderRadius: "var(--radius-md)", padding: "var(--space-4) var(--space-5)", minWidth: 140, flex: 1 }),
  kpiLabel: (tc = TC_LIGHT) => ({ fontSize: "var(--text-xs)", letterSpacing: "0.08em", textTransform: "uppercase", color: tc.textLight, fontWeight: 600, marginBottom: "var(--space-1)" }),
  kpiValue: (tc = TC_LIGHT, valueColor) => ({ fontSize: "var(--text-xl)", fontWeight: 700, color: valueColor ?? tc.navy, fontFamily: "'DM Mono',monospace" }),
  kpiSub: (tc = TC_LIGHT) => ({ fontSize: "var(--text-xs)", color: tc.textLight, marginTop: "var(--space-1)" }),
};

export const indexPageStyles = {
  page: (tc = TC_LIGHT, inline = false) => ({
    minHeight: inline ? undefined : "100vh",
    background: tc.bg,
    color: tc.text,
    fontFamily: "'Outfit',system-ui,sans-serif",
    fontSize: 14,
  }),
  topBar: (tc = TC_LIGHT) => ({
    background: tc.card,
    borderBottom: `1px solid ${tc.border}`,
    padding: "12px 32px",
    display: "flex",
    alignItems: "center",
    gap: 16,
  }),
  searchInput: (tc = TC_LIGHT) => ({
    padding: "var(--space-1) var(--space-3)",
    borderRadius: "var(--radius-md)",
    border: `1.5px solid ${tc.border}`,
    background: tc.bg,
    color: tc.text,
    fontSize: "var(--text-sm)",
    fontFamily: "inherit",
    width: 200,
    transition: "border-color 0.15s ease",
  }),
  navRow: (tc = TC_LIGHT, inline = false) => ({
    background: tc.card,
    borderBottom: `1px solid ${tc.border}`,
    padding: inline ? "0" : "0 32px",
    display: "flex",
    overflowX: "auto",
  }),
  navItem: (tc = TC_LIGHT, active = false) => ({
    background: "none",
    border: "none",
    borderBottom: `2px solid ${active ? tc.green : "transparent"}`,
    padding: "var(--space-3) var(--space-5)",
    fontSize: "var(--text-xs)",
    fontWeight: active ? 600 : 400,
    color: active ? tc.navy : tc.textMid,
    textDecoration: "none",
    fontFamily: "inherit",
    whiteSpace: "nowrap",
    cursor: "pointer",
    flexShrink: 0,
  }),
  contentWrap: {
    padding: "24px 32px",
  },
  panel: (tc = TC_LIGHT) => ({
    background: tc.card,
    border: `1px solid ${tc.border}`,
    borderRadius: 12,
    boxShadow: "0 2px 10px rgba(15, 23, 42, 0.04)",
    overflow: "hidden",
  }),
  tableScroll: {
    overflowX: "auto",
  },
  filterControl: (tc = TC_LIGHT) => ({
    width: "100%",
    padding: "var(--space-1) var(--space-2)",
    borderRadius: "var(--radius-sm)",
    border: `1px solid ${tc.border}`,
    background: tc.bg,
    color: tc.text,
    fontSize: "var(--text-xs)",
    fontFamily: "inherit",
    transition: "border-color 0.15s ease",
  }),
  clearButton: (tc = TC_LIGHT) => ({
    background: "transparent",
    border: `1px solid ${tc.border}`,
    borderRadius: "var(--radius-sm)",
    padding: "2px var(--space-2)",
    cursor: "pointer",
    fontSize: "var(--text-xs)",
    color: tc.textMid,
    fontFamily: "inherit",
    transition: "background 0.15s ease, border-color 0.15s ease",
  }),
};

