"""
Export monthly fund NAV prices per ISIN from fund_prices_combined.csv
to src/data/fundPrices.js (used by PriceHistoryChart).

Monthly resolution: keeps the last available price in each calendar month.
Filters: date >= 2019-01-01.

Usage:
    python scripts/fund_prices_export_js.py
"""

import csv
import json
import os
import datetime
from collections import defaultdict

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_IN  = os.path.join(BASE, "Mercats Públics", "fund_prices_combined.csv")
JS_OUT  = os.path.join(BASE, "src", "data", "fundPrices.js")

MIN_DATE = "2019-01-01"


def main():
    # monthly[isin][YYYY-MM] = last price seen for that month
    monthly = defaultdict(dict)

    with open(CSV_IN, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            date  = (row.get("date") or "").strip()
            isin  = (row.get("isin") or "").strip()
            close = (row.get("close") or "").strip()

            if not date or not isin or not close:
                continue
            if date < MIN_DATE:
                continue

            try:
                price = round(float(close), 4)
            except ValueError:
                continue

            month = date[:7]  # YYYY-MM
            monthly[isin][month] = price  # last row in month wins

    # Build sorted series per ISIN
    prices = {}
    for isin, mdict in sorted(monthly.items()):
        prices[isin] = [[m, p] for m, p in sorted(mdict.items())]

    # Write JS module
    today = datetime.date.today().isoformat()
    lines = [
        f"// Auto-generated by scripts/fund_prices_export_js.py — do not edit manually",
        f"// Generated: {today}",
        f"// Source: Mercats Públics/fund_prices_combined.csv",
        f"// Format: {{ [isin]: [['YYYY-MM', price], ...] }}  (monthly, from {MIN_DATE})",
        "",
        "export const FUND_PRICES = {",
    ]
    for isin, series in prices.items():
        lines.append(f'  "{isin}": {json.dumps(series, separators=(",", ":"))},')
    lines.append("};")
    lines.append("")

    with open(JS_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    total_points = sum(len(v) for v in prices.values())
    size_kb = os.path.getsize(JS_OUT) / 1024
    print(f"Exported {len(prices)} ISINs, {total_points:,} data points -> {JS_OUT}")
    print(f"File size: {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
