"""
Export monthly fund NAV prices per ISIN from the per-ISIN CSV files under
Mercats Públics/prices and Mercats Públics/fund_prices to src/generated/prices/fundPrices.js.

Monthly resolution keeps the last available price in each calendar month.

Usage:
    python scripts/fund_prices_export_js.py
"""

import csv
import datetime
import io
import json
import sys
from collections import defaultdict
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent.parent
PRICE_DIRS = [
    ROOT / "Mercats Públics" / "prices",
    ROOT / "Mercats Públics" / "fund_prices",
    ROOT / "Mercats Públics" / "wam_prices",
]
JS_OUT = ROOT / "src" / "generated" / "prices" / "fundPrices.js"

MIN_DATE = "2019-01-01"


def ingest_csv(csv_path: Path, series: dict[str, dict[str, tuple[str, float]]]) -> None:
    if not csv_path.exists():
        return
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            date = (row.get("date") or row.get("Date") or "").strip()
            if not date or date < MIN_DATE:
                continue

            close = row.get("close") or row.get("Close") or row.get("nav") or row.get("NAV")
            if close in (None, ""):
                continue

            try:
                price = round(float(close), 4)
            except ValueError:
                continue

            isin = (row.get("isin") or csv_path.stem).strip().upper()
            month = date[:7]
            prev = series[isin].get(month)
            if prev is None or date > prev[0]:
                series[isin][month] = (date, price)


def collect_monthly_prices(price_dirs: list[Path]) -> dict[str, list[list[float | str]]]:
    series = defaultdict(dict)
    for base in price_dirs:
        if not base.exists():
            continue
        for csv_path in sorted(base.glob("*.csv")):
            ingest_csv(csv_path, series)

    return {
        isin: [[month, value[1]] for month, value in sorted(months.items())]
        for isin, months in sorted(series.items())
        if months
    }


def main():
    if not any(d.exists() for d in PRICE_DIRS):
        print("ERROR: price directories not found.")
        raise SystemExit(1)

    prices = collect_monthly_prices(PRICE_DIRS)

    today = datetime.date.today().isoformat()
    lines = [
        "// Auto-generated by scripts/fund_prices_export_js.py — do not edit manually",
        f"// Generated: {today}",
        "// Sources: Mercats Públics/prices/*.csv and Mercats Públics/fund_prices/*.csv",
        f"// Format: {{ [isin]: [['YYYY-MM', price], ...] }}  (monthly, from {MIN_DATE})",
        "",
        "export const FUND_PRICES = {",
    ]
    for isin, monthly in prices.items():
        lines.append(f'  "{isin}": {json.dumps(monthly, separators=(",", ":"))},')
    lines.append("};")
    lines.append("")

    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text("\n".join(lines), encoding="utf-8")

    total_points = sum(len(v) for v in prices.values())
    print(f"Exported {len(prices)} ISINs, {total_points:,} data points -> {JS_OUT}")
    print(f"File size: {JS_OUT.stat().st_size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
