import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { RAW_CC } from "../src/data/capital-calls.js";
import { PORTFOLIO_COMPANIES } from "../src/data/searchers.js";
import { buildPrivateEntitiesFromDashboardBundle, resolvePrivateEntity } from "../src/data/privateEntities.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_PATH = path.resolve(__dirname, "../supabase/migrations/202604161900_private_entities_registry.sql");

function jsonbLiteral(tag, value) {
  return `$${tag}$${JSON.stringify(value)}$${tag}$::jsonb`;
}

const fundNames = [...new Set(RAW_CC.map((row) => row.fons))].sort();

const companyMappings = PORTFOLIO_COMPANIES.map((row) => ({
  nom: row.nom,
  entity_id: resolvePrivateEntity("company", row.nom, row.id ?? null)?.id ?? null,
}));

const fundMappings = fundNames.map((name) => ({
  fons: name,
  vehicle_id: resolvePrivateEntity("vehicle", name)?.id ?? null,
}));

const privateEntities = buildPrivateEntitiesFromDashboardBundle({
  companies: PORTFOLIO_COMPANIES.map((row) => ({ id: row.id ?? null, nom: row.nom })),
  rawCC: fundNames.map((fons) => ({ fons })),
});

const sql = `-- Migration: canonical private entity registry for alternatives
-- Generated by scripts/generate_private_entities_migration.mjs

create table if not exists public.private_entities (
  id text primary key,
  kind text not null check (kind in ('company', 'vehicle')),
  canonical_name text not null,
  source_name text,
  workbook_name text,
  match_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.capital_calls
  add column if not exists vehicle_id text;

alter table public.fund_meta
  add column if not exists vehicle_id text;

alter table public.fund_meta
  drop constraint if exists fund_meta_pkey;

alter table public.portfolio_companies
  add column if not exists entity_id text;

insert into public.private_entities (id, kind, canonical_name, source_name, workbook_name, match_type)
select id, kind, canonical_name, source_name, workbook_name, match_type
from jsonb_to_recordset(${jsonbLiteral("private_entities", privateEntities.map((row) => ({
  id: row.id,
  kind: row.kind,
  canonical_name: row.canonicalName,
  source_name: row.sourceName ?? row.canonicalName,
  workbook_name: row.workbookName ?? null,
  match_type: row.matchType ?? null,
})))})
  as x(id text, kind text, canonical_name text, source_name text, workbook_name text, match_type text)
on conflict (id) do update
set canonical_name = excluded.canonical_name,
    source_name = excluded.source_name,
    workbook_name = excluded.workbook_name,
    match_type = excluded.match_type,
    updated_at = now();

update public.portfolio_companies as c
set entity_id = x.entity_id
from jsonb_to_recordset(${jsonbLiteral("company_mappings", companyMappings)}) as x(nom text, entity_id text)
where c.entity_id is null
  and c.nom = x.nom;

update public.capital_calls as cc
set vehicle_id = x.vehicle_id
from jsonb_to_recordset(${jsonbLiteral("fund_mappings_cc", fundMappings)}) as x(fons text, vehicle_id text)
where cc.vehicle_id is null
  and cc.fons = x.fons;

update public.fund_meta as fm
set vehicle_id = x.vehicle_id
from jsonb_to_recordset(${jsonbLiteral("fund_mappings_meta", fundMappings)}) as x(fons text, vehicle_id text)
where fm.vehicle_id is null
  and fm.fons = x.fons;

update public.portfolio_companies as c
set nom = pe.canonical_name
from public.private_entities as pe
where c.entity_id = pe.id
  and c.nom is distinct from pe.canonical_name;

update public.capital_calls as cc
set fons = pe.canonical_name
from public.private_entities as pe
where cc.vehicle_id = pe.id
  and cc.fons is distinct from pe.canonical_name;

update public.fund_meta as fm
set fons = pe.canonical_name
from public.private_entities as pe
where fm.vehicle_id = pe.id
  and fm.fons is distinct from pe.canonical_name;

alter table public.capital_calls
  add constraint capital_calls_vehicle_id_fkey
  foreign key (vehicle_id) references public.private_entities(id)
  on update cascade on delete set null;

alter table public.fund_meta
  add constraint fund_meta_vehicle_id_key unique (vehicle_id);

alter table public.fund_meta
  add constraint fund_meta_vehicle_id_fkey
  foreign key (vehicle_id) references public.private_entities(id)
  on update cascade on delete set null;

alter table public.portfolio_companies
  add constraint portfolio_companies_entity_id_key unique (entity_id);

alter table public.portfolio_companies
  add constraint portfolio_companies_entity_id_fkey
  foreign key (entity_id) references public.private_entities(id)
  on update cascade on delete set null;

create index if not exists capital_calls_vehicle_id_idx
  on public.capital_calls(vehicle_id);

alter table public.private_entities enable row level security;

drop policy if exists private_entities_read_authenticated on public.private_entities;
create policy private_entities_read_authenticated
  on public.private_entities for select
  to authenticated
  using (true);

drop policy if exists private_entities_write_superuser on public.private_entities;
create policy private_entities_write_superuser
  on public.private_entities for all
  to authenticated
  using (public.is_superuser())
  with check (public.is_superuser());

create or replace function public.rename_private_entity(
  p_id text,
  p_name text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_superuser() then
    raise exception 'Forbidden';
  end if;

  if coalesce(length(trim(p_id)), 0) = 0 then
    raise exception 'Entity id required';
  end if;

  if coalesce(length(trim(p_name)), 0) = 0 then
    raise exception 'Entity name required';
  end if;

  update public.private_entities
  set canonical_name = trim(p_name),
      updated_at = now()
  where id = p_id;

  update public.capital_calls
  set fons = trim(p_name)
  where vehicle_id = p_id;

  update public.fund_meta
  set fons = trim(p_name)
  where vehicle_id = p_id;

  update public.portfolio_companies
  set nom = trim(p_name)
  where entity_id = p_id;
end;
$$;

create or replace function public.replace_dashboard_bundle(
  p_private_entities_rows jsonb,
  p_cc_rows jsonb,
  p_pl_rows jsonb,
  p_companies_rows jsonb,
  p_searchers_rows jsonb,
  p_fund_meta_rows jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_superuser() then
    raise exception 'Forbidden';
  end if;

  if p_cc_rows is not null then
    delete from public.capital_calls;
  end if;
  if p_cc_rows is not null and coalesce(jsonb_array_length(p_cc_rows), 0) > 0 then
    insert into public.capital_calls (vehicle_id, fons, tipus, cat, data, mes, year, fy, vcpe, est, eur, divisa)
    select vehicle_id, fons, tipus, cat, data, mes, year, fy, vcpe, est, eur, divisa
    from jsonb_to_recordset(coalesce(p_cc_rows, '[]'::jsonb))
      as x(vehicle_id text, fons text, tipus text, cat text, data text, mes integer, year integer, fy text, vcpe text, est text, eur numeric, divisa text);
  end if;

  if p_pl_rows is not null then
    delete from public.pipeline;
  end if;
  if p_pl_rows is not null and coalesce(jsonb_array_length(p_pl_rows), 0) > 0 then
    insert into public.pipeline (id, name, amount, currency, geography, strategy, sector, status, canal, active, estimated_closing)
    select id, name, amount, currency, geography, strategy, sector, status, canal, active, estimated_closing
    from jsonb_to_recordset(coalesce(p_pl_rows, '[]'::jsonb))
      as x(id integer, name text, amount numeric, currency text, geography text, strategy text, sector text, status text, canal text, active boolean, estimated_closing text);
  end if;

  if p_companies_rows is not null then
    delete from public.portfolio_companies;
  end if;
  if p_companies_rows is not null and coalesce(jsonb_array_length(p_companies_rows), 0) > 0 then
    insert into public.portfolio_companies (
      entity_id, nom, tipus, segment, entrepreneurs, origen, geo, ticket, tvpi, rvpi_eur, dpi_eur,
      rev, ebitda, dfn, gross_ev, mult_entry, data_compr, mesos_operant, is_mock, quarters
    )
    select
      entity_id, nom, tipus, segment, entrepreneurs, origen, geo, ticket, tvpi, rvpi_eur, dpi_eur,
      rev, ebitda, dfn, gross_ev, mult_entry, data_compr, mesos_operant, is_mock, coalesce(quarters, '[]'::jsonb)
    from jsonb_to_recordset(coalesce(p_companies_rows, '[]'::jsonb))
      as x(
        entity_id text, nom text, tipus text, segment text, entrepreneurs text, origen text, geo text,
        ticket numeric, tvpi numeric, rvpi_eur numeric, dpi_eur numeric,
        rev numeric, ebitda numeric, dfn numeric, gross_ev numeric, mult_entry numeric,
        data_compr text, mesos_operant integer, is_mock boolean, quarters jsonb
      );
  end if;

  if p_searchers_rows is not null then
    delete from public.searchers;
  end if;
  if p_searchers_rows is not null and coalesce(jsonb_array_length(p_searchers_rows), 0) > 0 then
    insert into public.searchers (
      nom, tipus, modalitat, geo, status_screening, form_entrada, intro_per, searcher1, searcher2,
      escola1, escola2, ticket, data_inici, data_compr, mesos_cercant, equity_stake, is_mock
    )
    select
      nom, tipus, modalitat, geo, status_screening, form_entrada, intro_per, searcher1, searcher2,
      escola1, escola2, ticket, data_inici, data_compr, mesos_cercant, equity_stake, is_mock
    from jsonb_to_recordset(coalesce(p_searchers_rows, '[]'::jsonb))
      as x(
        nom text, tipus text, modalitat text, geo text, status_screening text, form_entrada text, intro_per text,
        searcher1 text, searcher2 text, escola1 text, escola2 text, ticket numeric, data_inici text, data_compr text,
        mesos_cercant integer, equity_stake numeric, is_mock boolean
      );
  end if;

  if p_fund_meta_rows is not null then
    delete from public.fund_meta;
  end if;

  if p_private_entities_rows is not null then
    delete from public.private_entities
    where kind in ('company', 'vehicle');
  end if;
  if p_private_entities_rows is not null and coalesce(jsonb_array_length(p_private_entities_rows), 0) > 0 then
    insert into public.private_entities (id, kind, canonical_name, source_name, workbook_name, match_type)
    select id, kind, canonical_name, source_name, workbook_name, match_type
    from jsonb_to_recordset(coalesce(p_private_entities_rows, '[]'::jsonb))
      as x(id text, kind text, canonical_name text, source_name text, workbook_name text, match_type text);
  end if;

  if p_fund_meta_rows is not null and coalesce(jsonb_array_length(p_fund_meta_rows), 0) > 0 then
    insert into public.fund_meta (vehicle_id, fons, tvpi)
    select vehicle_id, fons, tvpi
    from jsonb_to_recordset(coalesce(p_fund_meta_rows, '[]'::jsonb))
      as x(vehicle_id text, fons text, tvpi numeric);
  end if;
end;
$$;
`;

fs.writeFileSync(OUTPUT_PATH, sql, "utf8");
