import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import {
  PM_CLOSED,
  PM_LIQUIDITY_POSITIONS,
  PM_MANAGERS,
  PM_MONTHLY,
  PM_POSITION_ID_ALIASES,
  PM_POSITIONS,
  PM_POSITIONS_RAW,
  PM_TOTAL_ACTIVE,
  PM_TOTAL_LIQUIDITY,
  PM_TOTAL_WORKBOOK_ROW,
} from "../src/data/publicMarkets.js";
import { PM_CLOSED_VALUES } from "../src/data/pmClosedValues.js";
import { PM_TRANSACTIONS } from "../src/generated/publicMarkets/pmTransactions.js";
import { PM_VALUES } from "../src/generated/publicMarkets/portfolioValues.js";

/** @typedef {import("../src/data/publicMarketsTypes.js").PMModelGenerated} PMModelGenerated */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..");
const OUT_JS = path.join(ROOT, "src", "generated", "publicMarkets", "publicMarketsModel.generated.js");

/** @type {PMModelGenerated} */
const PM_MODEL_GENERATED = {
  holdings: {
    active: PM_POSITIONS,
    activeRaw: PM_POSITIONS_RAW,
    closed: PM_CLOSED,
    liquidity: PM_LIQUIDITY_POSITIONS,
  },
  activity: {
    transactions: PM_TRANSACTIONS,
  },
  series: {
    values: PM_VALUES,
    monthly: PM_MONTHLY,
    closedValues: PM_CLOSED_VALUES,
  },
  metadata: {
    managers: PM_MANAGERS,
    positionIdAliases: PM_POSITION_ID_ALIASES,
    totals: {
      active: PM_TOTAL_ACTIVE,
      liquidity: PM_TOTAL_LIQUIDITY,
      workbookRow: PM_TOTAL_WORKBOOK_ROW,
    },
  },
};

const out = [
  "// Auto-generated by scripts/pm_model_export_js.mjs — do not edit manually",
  "// Run npm run pm:refresh to rebuild the canonical PM model export",
  `export const PM_MODEL_GENERATED = ${JSON.stringify(PM_MODEL_GENERATED)};`,
  "",
].join("\n");

fs.mkdirSync(path.dirname(OUT_JS), { recursive: true });
fs.writeFileSync(OUT_JS, out, "utf8");

console.log(`Active holdings:   ${PM_MODEL_GENERATED.holdings.active.length}`);
console.log(`Closed holdings:   ${PM_MODEL_GENERATED.holdings.closed.length}`);
console.log(`Transactions:      ${PM_MODEL_GENERATED.activity.transactions.length}`);
console.log(`Value series ISINs:${Object.keys(PM_MODEL_GENERATED.series.values).length}`);
console.log(`Output:            ${OUT_JS}`);
