"""
portfolio_export_js.py
──────────────────────
Reads Mercats Públics/portfolio_value.csv and exports monthly-aggregated
portfolio values as a JavaScript module for use in the dashboard.

Output: src/data/portfolioValues.js

Usage:
    python scripts/portfolio_export_js.py

Run after portfolio_build_values.py.
"""
import io
import json
import sys
from pathlib import Path

import pandas as pd

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT   = Path(__file__).parent.parent
IN_CSV = ROOT / "Mercats Públics" / "portfolio_value.csv"
OUT_JS = ROOT / "src" / "data" / "portfolioValues.js"


def main():
    if not IN_CSV.exists():
        print(f"ERROR: {IN_CSV} not found. Run portfolio_build_values.py first.")
        sys.exit(1)

    df = pd.read_csv(IN_CSV, parse_dates=["date"])
    df["month"] = df["date"].dt.to_period("M").astype(str)  # "2024-01"

    # Keep last row per (isin, custodian, month)
    df = df.sort_values("date")
    monthly = (
        df.groupby(["isin", "custodian", "month"], sort=False)
        .last()
        .reset_index()
    )

    # Build nested dict: { isin: { custodian: [{date, value}] } }
    result = {}
    for (isin, custodian), grp in monthly.groupby(["isin", "custodian"]):
        rows = (
            grp.sort_values("month")[["month", "value_eur"]]
            .rename(columns={"month": "date", "value_eur": "value"})
        )
        rows = rows.copy()
        rows["value"] = rows["value"].round(0).astype(int)
        if isin not in result:
            result[isin] = {}
        result[isin][custodian] = rows.to_dict(orient="records")

    payload = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    out = (
        "// Auto-generated by scripts/portfolio_export_js.py — do not edit manually\n"
        "// Run scripts/portfolio_export_js.py to populate with real data\n"
        f"export const PM_VALUES = {payload};\n"
    )
    OUT_JS.write_text(out, encoding="utf-8")

    total_rows = sum(
        len(rows)
        for isin_data in result.values()
        for rows in isin_data.values()
    )
    print(f"ISINs:        {len(result)}")
    print(f"Series:       {sum(len(v) for v in result.values())}")
    print(f"Monthly rows: {total_rows}")
    print(f"Output:       {OUT_JS}")


if __name__ == "__main__":
    main()
