"""
portfolio_export_js.py
──────────────────────
Reads Mercats Públics/portfolio_value.csv and exports bi-weekly-aggregated
portfolio values as a JavaScript module for use in the dashboard.

Each date is bucketed to the nearest prior 1st or 15th of the month.
Date keys are ISO "YYYY-MM-DD" strings (e.g. "2024-01-01", "2024-01-15").

Output: src/data/portfolioValues.js

Usage:
    python scripts/portfolio_export_js.py

Run after portfolio_build_values.py.
"""
import io
import json
import sys
from pathlib import Path

import pandas as pd

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT   = Path(__file__).parent.parent
IN_CSV = ROOT / "Mercats Públics" / "portfolio_value.csv"
OUT_JS = ROOT / "src" / "data" / "portfolioValues.js"


def biweekly_bucket(dt) -> str:
    """Map a date to the nearest prior 1st or 15th of the month → 'YYYY-MM-DD'."""
    day = dt.day
    anchor = 1 if day < 15 else 15
    return f"{dt.year:04d}-{dt.month:02d}-{anchor:02d}"


def main():
    if not IN_CSV.exists():
        print(f"ERROR: {IN_CSV} not found. Run portfolio_build_values.py first.")
        sys.exit(1)

    df = pd.read_csv(IN_CSV, parse_dates=["date"])
    df["bucket"] = df["date"].apply(biweekly_bucket)

    # Keep last row per (isin, custodian, bucket)
    df = df.sort_values("date")
    bucketed = (
        df.groupby(["isin", "custodian", "bucket"], sort=False)
        .last()
        .reset_index()
    )

    # Build nested dict: { isin: { custodian: [{date, value}] } }
    result = {}
    for (isin, custodian), grp in bucketed.groupby(["isin", "custodian"]):
        rows = (
            grp.sort_values("bucket")[["bucket", "value_eur"]]
            .rename(columns={"bucket": "date", "value_eur": "value"})
        )
        rows = rows.copy()
        rows["value"] = rows["value"].round(0).astype(int)
        if isin not in result:
            result[isin] = {}
        result[isin][custodian] = rows.to_dict(orient="records")

    payload = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    out = (
        "// Auto-generated by scripts/portfolio_export_js.py — do not edit manually\n"
        "// Run scripts/portfolio_export_js.py to populate with real data\n"
        f"export const PM_VALUES = {payload};\n"
    )
    OUT_JS.write_text(out, encoding="utf-8")

    total_rows = sum(
        len(rows)
        for isin_data in result.values()
        for rows in isin_data.values()
    )
    print(f"ISINs:         {len(result)}")
    print(f"Series:        {sum(len(v) for v in result.values())}")
    print(f"Bi-weekly rows:{total_rows}")
    print(f"Output:        {OUT_JS}")


if __name__ == "__main__":
    main()
