"""
ter_export_js.py
────────────────
Reads Mercats Públics/fund_ter.json and exports a JS module for the dashboard.

Output: src/generated/publicMarkets/pmTer.js   →   export const PM_TER = { [isin]: ter_pct, ... }

TER values are floating-point percentages (e.g. 0.07 for 0.07%).

Usage:
    python scripts/ter_export_js.py

Run after fund_fetch_ter.py.
"""

import io
import json
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT     = Path(__file__).parent.parent
IN_JSON  = ROOT / "Mercats Públics" / "fund_ter.json"
OUT_JS   = ROOT / "src" / "generated" / "publicMarkets" / "pmTer.js"


def main():
    if not IN_JSON.exists():
        print(f"ERROR: {IN_JSON} not found. Run fund_fetch_ter.py first.")
        sys.exit(1)

    data: dict[str, float] = json.loads(IN_JSON.read_text(encoding="utf-8"))
    payload = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))

    out = (
        "// Auto-generated by scripts/ter_export_js.py — do not edit manually\n"
        "// Run scripts/fund_fetch_ter.py then scripts/ter_export_js.py to update\n"
        f"export const PM_TER = {payload};\n"
    )
    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text(out, encoding="utf-8")

    print(f"ISINs exported: {len(data)}")
    print(f"Output:         {OUT_JS}")

    # Sample
    for isin, ter in sorted(data.items())[:5]:
        print(f"  {isin}: {ter}%")


if __name__ == "__main__":
    main()
