/**
 * Parses turtle-fons-model.xlsx and exports src/generated/dashboard/turtleFonsModel.js.
 *
 * Excel layout (model sheet):
 *   Row 3  (0-idx): header — col 1 = empty, col 2 = "Capital compromés", col 3+ = years
 *   Every fund block is 5 rows:
 *     Row +0: fund name (col 1), committed capital (col 2), annual call amounts (col 3+)
 *     Row +1: % desemborsaments (skipped)
 *     Row +2: "Distribucions anuals" (col 1), annual distribution amounts (col 3+)
 *     Row +3: % distribucions (skipped)
 *     Row +4: empty separator
 *
 * Output: editorData-compatible object { years, funds: { [name]: { committed, model_calls, model_dist } } }
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import XLSX from "./lib/xlsx_compat.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const INPUT  = path.join(ROOT, "turtle-fons-model.xlsx");
const OUT_JS = path.join(ROOT, "src", "generated", "dashboard", "turtleFonsModel.js");

const wb = await XLSX.readFile(INPUT);
const raw = XLSX.utils.sheet_to_json(wb.Sheets["model"], { header: 1, defval: null });

// ── Parse header row ──────────────────────────────────────────────────────────
const headerRow = raw[3];
const YEAR_START_COL = 3;
const years = [];
for (let c = YEAR_START_COL; c < headerRow.length; c++) {
  const v = headerRow[c];
  if (typeof v === "number" && v >= 2019 && v <= 2040) years.push(v);
}

// ── Parse fund blocks ─────────────────────────────────────────────────────────
const funds = {};
let i = 4; // first row after header
while (i < raw.length) {
  const r = raw[i];
  const name = typeof r?.[1] === "string" ? r[1].trim() : null;
  const committed = typeof r?.[2] === "number" ? r[2] : null;

  // Detect fund row: has a string name and a numeric committed capital
  if (!name || committed == null) { i++; continue; }

  const model_calls = {};
  for (let c = 0; c < years.length; c++) {
    const v = r[YEAR_START_COL + c];
    if (typeof v === "number" && v > 0) model_calls[years[c]] = Math.round(v * 100) / 100;
  }

  // Distributions row is +2 from the fund row
  const distRow = raw[i + 2] ?? [];
  const model_dist = {};
  for (let c = 0; c < years.length; c++) {
    const v = distRow[YEAR_START_COL + c];
    if (typeof v === "number" && v > 0) model_dist[years[c]] = Math.round(v * 100) / 100;
  }

  funds[name] = { committed, model_calls, model_dist };
  i += 5; // skip the 4-row block + empty separator
}

// ── Emit JS ───────────────────────────────────────────────────────────────────
const fundCount = Object.keys(funds).length;
const banner = `// Auto-generated by scripts/turtle_fons_export_js.mjs — do not edit manually
// Source: turtle-fons-model.xlsx  (${fundCount} funds, ${years[0]}–${years.at(-1)})
// Run: node scripts/turtle_fons_export_js.mjs
`;

function serialize(obj) {
  // Only unquote keys that are valid bare JS identifiers (letters/digits/$/_), no spaces/special chars.
  return JSON.stringify(obj, null, 2).replace(/"([^"]+)":/g, (match, k) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? `${k}:` : match
  );
}

const body = `${banner}
export const TURTLE_FONS_MODEL = ${serialize({ years, funds })};
`;

fs.writeFileSync(OUT_JS, body, "utf8");
console.log(`Wrote ${OUT_JS} — ${fundCount} funds, years ${years[0]}–${years.at(-1)}`);
