/**
 * Parses a fund cashflow model workbook and exports
 * src/generated/dashboard/turtleFonsModel.js.
 *
 * Excel layout:
 *   Header row contains "Capital compromés", followed by year columns.
 *   Every fund block is 5 rows:
 *     Row +0: fund name, committed capital, annual call amounts
 *     Row +1: % desemborsaments (skipped)
 *     Row +2: "Distribucions anuals", annual distribution amounts
 *     Row +3: % distribucions (skipped)
 *     Row +4: empty separator
 *
 * Output: editorData-compatible object { years, funds: { [name]: { committed, model_calls, model_dist } } }
 *
 * Usage:
 *   node scripts/turtle_fons_export_js.mjs [workbook.xlsx]
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import XLSX from "./lib/xlsx_compat.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const inputArg = process.argv[2] ?? "turtle-fons-model.xlsx";
const INPUT = path.isAbsolute(inputArg) ? inputArg : path.join(ROOT, inputArg);
const OUT_JS = path.join(ROOT, "src", "generated", "dashboard", "turtleFonsModel.js");

const wb = await XLSX.readFile(INPUT);
const sheetName = wb.Sheets["model"] ? "model" : wb.SheetNames[0];
const raw = XLSX.utils.sheet_to_json(wb.Sheets[sheetName], { header: 1, defval: null });

// -- Parse header row ----------------------------------------------------------
const headerIndex = raw.findIndex((row) => row.some((value) => String(value ?? "").trim() === "Capital compromés"));
if (headerIndex < 0) throw new Error(`No "Capital compromés" header found in ${INPUT}`);
const headerRow = raw[headerIndex];
const committedCol = headerRow.findIndex((value) => String(value ?? "").trim() === "Capital compromés");
const nameCol = committedCol - 1;
const YEAR_START_COL = committedCol + 1;
const years = [];
for (let c = YEAR_START_COL; c < headerRow.length; c++) {
  const v = headerRow[c];
  if (typeof v === "number" && v >= 2019 && v <= 2040) years.push(v);
}

// -- Parse fund blocks ---------------------------------------------------------
const funds = {};
let i = headerIndex + 1;
while (i < raw.length) {
  const r = raw[i];
  const name = typeof r?.[nameCol] === "string" ? r[nameCol].trim() : null;
  const committed = typeof r?.[committedCol] === "number" ? r[committedCol] : null;

  // Detect fund row: has a string name and a numeric committed capital.
  if (!name || committed == null) { i++; continue; }

  const model_calls = {};
  for (let c = 0; c < years.length; c++) {
    const v = r[YEAR_START_COL + c];
    if (typeof v === "number" && v > 0) model_calls[years[c]] = Math.round(v * 100) / 100;
  }

  const distRow = raw[i + 2] ?? [];
  const model_dist = {};
  for (let c = 0; c < years.length; c++) {
    const v = distRow[YEAR_START_COL + c];
    if (typeof v === "number" && v > 0) model_dist[years[c]] = Math.round(v * 100) / 100;
  }

  funds[name] = { committed, model_calls, model_dist };
  i += 5;
}

// -- Emit JS -------------------------------------------------------------------
const fundCount = Object.keys(funds).length;
const sourceName = path.relative(ROOT, INPUT).replace(/\\/g, "/") || path.basename(INPUT);
const banner = `// Auto-generated by scripts/turtle_fons_export_js.mjs - do not edit manually
// Source: ${sourceName}  (${fundCount} funds, ${years[0]}-${years.at(-1)})
// Run: node scripts/turtle_fons_export_js.mjs ${sourceName}
`;

function serialize(obj) {
  // Only unquote keys that are valid bare JS identifiers (letters/digits/$/_), no spaces/special chars.
  return JSON.stringify(obj, null, 2).replace(/"([^"]+)":/g, (match, k) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? `${k}:` : match
  );
}

const body = `${banner}
export const TURTLE_FONS_MODEL = ${serialize({ years, funds })};
`;

fs.writeFileSync(OUT_JS, body, "utf8");
console.log(`Wrote ${OUT_JS} - ${fundCount} funds, years ${years[0]}-${years.at(-1)}`);
