-- Remove searcher rows that are not in the Excel Master sheet.
-- Source of truth: 260416_Seguiment_SearchFunds.xlsx, "Master" tab.
-- Entries like Avatel, Itaca, Baluard were added manually or via old imports
-- and are not search funds.

DELETE FROM searchers
WHERE trim(nom) NOT IN (
  'Primus Transmission',
  'Emptio Capital',
  'Norland Equity Partners',
  'Gare Capital',
  'Phoenix Rise Capital',
  'Acacia Capital',
  'Agripina Capital',
  'Aquilae Relevo',
  'Kramer Inversiones',
  'KG Capital',
  'Quo Inversión',
  'Miraflores Capital',
  'Omura Capital',
  'Hargrave Succession',
  'Somontano Capital',
  'Oportuna Capital',
  'Road Capital',
  'Impetu Capital',
  'Stellaris Capital Partners',
  'AJS Capital',
  'December Transmission',
  'Dangalena Capital',
  'Vareco Capital',
  'Ashington Capital',
  'Luceiro Capital',
  'Primrose Capital Partners',
  'Lexana Capital',
  'Wildlynx Capital, SL',
  'Pleamar Partners',
  'Relevian',
  'Konkordia',
  'Salomonte',
  'Continuation Partners',
  'Almond Capital',
  'Aeqor Partners',
  'Tasman Capital',
  'AB1',
  'Eureka Capital',
  'Telos Invest',
  'Mahogany',
  'Lakeview Partners',
  'Renovatio Capital',
  'AdAstra Partners',
  'Anval Capital',
  'Criluz Capital',
  'Terra Firma Capital',
  'SCL',
  'Fortius FS',
  'Annapurna Capital',
  'Fairmile Partners',
  'IBV',
  'Nela Succession Fund',
  'Jaguar Stork',
  'Farnam Entrepreneurial Succession',
  'Harvest Capital',
  'Versa Capital',
  'Sapiens Capital',
  'Nautilus',
  'Tinto Hill',
  'Boyere Capital',
  'Rumbo Capital Partners',
  'Vitis Capital',
  'Viriato Capital',
  'Nobis Capital',
  'FSJ',
  'Bitacora Partners',
  'Nudo Capital Partners',
  'Ayete Partners',
  'Orión Capital',
  'Bentayga Capital',
  'Imagine+',
  'ADA Capital',
  'Divisadero Capital',
  'Black Fox Invest',
  'Leonessa Capital',
  'Guise Capital',
  'Lima capital',
  'Pontem Capital',
  'Maruna Capital',
  'Alpinuum Nachfolge',
  'Bocanegra Group',
  'Arianna Capital',
  'Perseus Capital',
  'Pharus Succession Management',
  'Alpina Transmission',
  'Fidelis Capital Partners',
  'Entredos Capital',
  'Dymond Capital',
  'Spera Capital',
  'Eschen Fond',
  'RNP Growth',
  'P&P Partners',
  'Ice Pond Capital',
  'Patanjali Capital',
  'Nutria Capital',
  'Sisal Capital',
  '7iron Capital',
  'Audaz Capital',
  'Enlace Capital',
  'NCA SF 77',
  'Italcraft',
  'Lynx Trial Capital',
  'NCA SF 34',
  'AMZ Capital',
  'Sachem Partners',
  'Big Tower Group',
  'Quercus Transmission',
  'Oakstreet',
  'Quercus Investments',
  'Legatum Capital Partners',
  'Targos Group',
  'Elcano Finanture',
  'Soclofi Transmission',
  'Preludio Partners',
  'Norte Partners',
  'Thames Equity Partners',
  'Batis Capital',
  'Vericor Capital',
  'Mentmore Capital',
  'JCTC',
  'Project Stella',
  'Summit Capital',
  'Pros Partners',
  'JC Partners',
  'Olympia',
  'Emme Art Capital',
  'Juxon Capital',
  'Avancer Transmission',
  'TEC Capital',
  'Alino Invest',
  'Albatross Partners',
  'HW Capital Group Limited',
  'Memorable Capital',
  'Sunrise Capital',
  'Cassandra Investments',
  'Covadonga Capital',
  'Alchemist',
  'Activation Partners',
  'B2R Investments',
  'Fonteyn Partners',
  'Logos Equity Partners',
  'Vestran',
  'TwentyTwo Capital',
  'Indus Capital',
  'Caupa Capital',
  'MMP Capital',
  'Seqos',
  'Notus Capital',
  'Intuito Capital',
  'Palette Capital',
  'Nephos Capital',
  'Artemide Capital Partners',
  'Adarve Capital',
  'Alpha Nova Capital',
  'W&M Succession Partners',
  'Muro Partners',
  'Scrum Capital',
  'Virrey Capital Partners',
  'L&C Capital',
  'Janus Mittelstandnachfolge',
  'Handriv Capital',
  'Siete Picos',
  'Continuum Capital',
  'Olta Nachfolge',
  'Nortem Capital',
  'P1VP',
  'Hidden Star Capital',
  'Castelnau Capital',
  'Porast Search Fund',
  'Tesela Capital',
  'Marmore Capital',
  'Acquisisco',
  'Origo Capital',
  'Rigi Capital',
  'Sly Capital',
  'Aneto Partners',
  'AJD Partners',
  'Augustine Bridge',
  'BrennPoint',
  'Epicea Transmission',
  'Vinea Partners',
  'Project Cardboard',
  'Reviva Holding',
  'Semita Capital',
  'Legare',
  'Mediterraneum Partners',
  'Harbor Crest',
  'Project Root',
  'Mainstay Ventures',
  'Leon Ventures',
  'Ergon Capital',
  'Cenia Inversiones',
  'Drita Capital Partners',
  'Ascari Capital',
  'Terragora Capital'
);
